name: covid19-bal-atlas
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - docopt
  - r-docopt
  - rpy2
  - scanpy
  - r-seurat
  - r-biocmanager
  - bioconductor-scran
  - bioconductor-scater
  - bioconductor-zellkonverter
  - r-readxl
  - r-viridis
  - r-remotes
  - notebook
  - r-irkernel
